config/routes.rb
Rails.application.routes.draw do

  resources :types
  devise_for :users

  root to: 'static#home'

  resources :leasings
  resources :bills
  resources :brands
  resources :vehicles
  resources :models
  resources :users
  get '/louer/vehicule/:id', to: 'leasings#new', as:'louer'
  get '/demande/vehicule/:id', to: 'leasings#create', as:'demande'

  namespace :ad do
    resources :bills
    resources :leasings
    resources :brands
    resources :vehicles
    resources :models
    resources :users

    root :to => "static#home"
  end

end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :models



  validates_presence_of(
  :name,
  :logo,
  :history
  )

  #donne le nombre de model par page
  self.per_page = 20
  mount_uploader :logo, PhotoUploader
end

app/controllers/ad/base_controller.rb
# frozen_string_literal: true

module Ad
  # for layout
  class BaseController < ::ApplicationController
    before_action :authenticate_admin
    layout 'ad/application'
   # before_action :set_access
    def authenticate_admin
      if !user_signed_in? || current_user.role.name != 'admin'
        redirect_to new_user_path, danger: "Vous n'avez pas le droit d'accéder à cette page"
      end
    end
  end
end

app/controllers/ad/bills_controller.rb
module Ad
class BillsController < BaseController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    #page params[:page] donne la page pour la pagination
    @bills = Bill.page params[:page]
  end

  # GET /bills/1
  # GET /bills/1.json
  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)

    respond_to do |format|
      if @bill.save
        format.html { redirect_to @bill, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        format.html { redirect_to @bill, notice: 'Bill was successfully updated.' }
        format.json { render :show, status: :ok, location: @bill }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy
    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.fetch(:bill, {})
    end
end
end

app/controllers/ad/brands_controller.rb
module Ad
class BrandsController < BaseController
  before_action :set_brand, only: [:show, :edit, :update, :destroy]

  # GET /brands
  # GET /brands.json
  def index
    #page params[:page] donne la page pour la pagination
    @brands = Brand.page params[:page]
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brand
      @brand = Brand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brand_params
      params.fetch(:brand).permit( :name )
    end
end
  end

app/controllers/ad/leasings_controller.rb
module Ad
    class LeasingsController < BaseController
      before_action :set_leasing, only: [:show, :edit, :update, :destroy]

      # GET /leasings
      # GET /leasings.json
      def index
        #page params[:page] donne la page pour la pagination

        @q = Leasing.order(created_at: :DESC).ransack(params[:q])
        @leasings = @q.result.includes(:user, :vehicle).page params[:page]
      end

      # GET /leasings/1
      # GET /leasings/1.json
      def show
      end

      # GET /leasings/new
      def new
        @leasing = Leasing.new
      end

      # GET /leasings/1/edit
      def edit
      end

      # POST /leasings
      # POST /leasings.json
      def create
        @leasing = Leasing.new(leasing_params)

        respond_to do |format|
          if @leasing.save
            format.html { redirect_to @leasing, notice: 'Leasing was successfully created.' }
            format.json { render :show, status: :created, location: @leasing }
          else
            format.html { render :new }
            format.json { render json: @leasing.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /leasings/1
      # PATCH/PUT /leasings/1.json
      def update
        respond_to do |format|
          if @leasing.update(leasing_params) && leasing_params["approved"] = false
            format.html { redirect_to ad_leasing_path(@leasing), notice: 'Leasing was successfully updated.' }
            format.json { render :show, status: :ok, location: @leasing }
          elsif leasing_params["approved"] = true
            @bill = Bill.new()
            @bill.ht =(@leasing.end_date.to_date -  @leasing.beginning_date.to_date).to_i * @leasing.vehicle.price
            @bill.ttc = @bill.ht * 1.20
            fidelity = (@leasing.user.fidelity.to_f / 100).to_f * @bill.ttc.to_f
            @bill.total = @bill.ttc.to_f - fidelity
            @bill.deadline = @leasing.beginning_date + 30
            @bill.leasing_id = @leasing.id
            @bill.paid = false
            @bill.num_bill = Bill.last.num_bill + 1
            if @leasing.update(leasing_params) && @bill.save
              format.html { redirect_to ad_bill_path(@bill), notice: 'La facture a etait créé' }
              format.json { render :show, status: :ok, location: @leasing }
              end
          else
            format.html { render :edit }
            format.json { render json: @leasing.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /leasings/1
      # DELETE /leasings/1.json
      def destroy
        @leasing.destroy
        respond_to do |format|
          format.html { redirect_to leasings_url, notice: 'Leasing was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_leasing
          @leasing = Leasing.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def leasing_params
          params.fetch(:leasing).permit(
                             :beginning_date,
                             :end_date,
                             :limit_km,
                             :penelty,
                             :user_id,
                             :vehicle_id
          )
        end
    end
end

app/controllers/ad/models_controller.rb
module Ad
class ModelsController < BaseController
  before_action :set_model, only: [:show, :edit, :update, :destroy]

  # GET /models
  # GET /models.json
  def index
    #page params[:page] donne la page pour la pagination
    @models = Model.page params[:page]
  end

  # GET /models/1
  # GET /models/1.json
  def show
  end

  # GET /models/new
  def new
    @model = Model.new
  end

  # GET /models/1/edit
  def edit
  end

  # POST /models
  # POST /models.json
  def create
    @model = Model.new(model_params)

    respond_to do |format|
      if @model.save
        format.html { redirect_to @model, notice: 'Model was successfully created.' }
        format.json { render :show, status: :created, location: @model }
      else
        format.html { render :new }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /models/1
  # PATCH/PUT /models/1.json
  def update
    respond_to do |format|
      if @model.update(model_params)
        format.html { redirect_to @model, notice: 'Model was successfully updated.'}
        format.json { render :show, status: :ok, location: @model }
      else
        format.html { render :edit }
        format.json { render json: @model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /models/1
  # DELETE /models/1.json
  def destroy
    @model.destroy
    respond_to do |format|
      format.html { redirect_to models_url, notice: 'Model was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_model
      @model = Model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def model_params
      params.require(:model).permit( :name, :brand_id )
    end
end
end

app/controllers/ad/static_controller.rb
module Ad
  class StaticController < BaseController
    def home
      @bills = Bill.order(:created_at).limit(5)
      @leasings = Leasing.order(:created_at).limit(5)
    end
  end
end

app/controllers/ad/types_controller.rb
module Ad
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.all
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.fetch(:type, {})
    end
end

  end

app/controllers/ad/users_controller.rb
module Ad
class UsersController < BaseController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    #page params[:page] donne la page pour la pagination
    @users = User.page params[:page]
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
          :first_name,
          :last_name,
          :email,
          :phone,
          :number_permie,
          :password,
          :password_confirmation,
          :street,
          :city,
          :zipcode,
          :fidelity
        )
    end
end
  end

app/controllers/ad/vehicles_controller.rb
module Ad
class VehiclesController < BaseController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    #page params[:page] donne la page pour la pagination
    @vehicles = Vehicle.page params[:page]
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def vehicle_params
    params.fetch(:vehicle).permit(
          :num_serial,
          :color,
          :numberplate,
          :num_km,
          :buying_date,
          :buying_price,
          :model_id
    )
  end
end
  end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/ad/brands/_form.html.erb
<%= form_with(model: brand, local: true, url: ad_brands_path) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>
      <ul>
        <% brand.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="row">
      <div class="col-lg-4 mb-5">
        <div class="row form-group">
          <p class="mx-auto"><%= image_tag(@brand.logo_url) if @brand.logo? %></p>
        </div>
        <div class="row form-group my-auto">
          <div class="col-12 col-md-12">
            <%= form.file_field :logo, id: :brand_logo, class: "form-control-file" %>
            <%= form.hidden_field :logo_cache %>
          </div>
        </div>
      </div>
      <div class="col-lg-8 mt-auto mb-auto">
        <div class="row form-group">
          <div class="col col-md-2">
            <%= form.label :name, "Nom", class: "form-control-label"%>
          </div>
          <div class="col-12 col-md-10">
            <!--<input type="text" id="text-input" name="text-input" placeholder="Text" class="form-control">-->
            <%= form.text_field :name, class: "form-control", placeholder: "Nom" %>
          </div>
        </div>
        <div class="row form-group">
          <div class="col col-md-2">
            <%= form.label :history, "Histoire", class: "form-control-label" %>
          </div>
          <div class="col-12 col-md-10">
            <%= form.text_area :history, rows: "7", class: "form-control", placeholder: "Histoire..." %>
          </div>
        </div>
      </div>
    </div>
    <div class="row float-right mt-5">
      <%= form.submit "Enregistrer", class: "btn btn-success btn-lg" %>
      <button type="reset" class="btn btn-danger btn-lg">
        <%= link_to "Annuler", ad_brands_path, class:"color-white" %>
      </button>
    </div>
  </div>
<% end %>

app/views/ad/brands/edit.html.erb
<div class="breadcrumbs">
  <div class="col-sm-4">
    <div class="page-header float-left">
      <div class="page-title">
        <h1>
          <%= @brand.name %>
        </h1>
      </div>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="page-header float-right">
      <div class="page-title">
        <ol class="breadcrumb text-right">
          <li class="active">
            <%= link_to 'Marques', ad_brands_path %> / <%= link_to @brand.name, ad_brands_path %> / Modifier
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>
<p id="notice"><%= notice %></p>
<div class="content mt-3">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <strong class="card-title">Modifier la marque</strong>
          </div>
          <div class="card-body">
            <div id="pay-invoice">
              <div class="card-body">
                <div class="card-title">
                  <h3 class="text-center"><%= @brand.name %></h3>
                </div>
                <%= render 'form', brand: @brand %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div><!--DO NOT DELETE close right-panel in header.html.erb DO NOT DELETE-->

app/views/ad/brands/index.html.erb
<div class="breadcrumbs">
  <div class="col-sm-4">
    <div class="page-header float-left">
      <div class="page-title">
        <h1>
          Marques
        </h1>
      </div>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="page-header float-right">
      <div class="page-title">
        <ol class="breadcrumb text-right">
          <li class="active">Marques</li>
        </ol>
      </div>
    </div>
  </div>
</div>
<p id="notice"><%= notice %></p>
<div class="content mt-3">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <strong class="card-title">
              Marques
              <div class="float-right">
                <%= link_to raw("<i class='fa fa-plus' aria-hidden='true'></i> Ajouter"), new_ad_brand_path, class: "btn btn-primary btn-sm" %>
              </div>
            </strong>
          </div>
          <div class="card-body">
            <table id="bootstrap-data-table" class="table table-striped table-bordered">
              <thead>
              <tr>
                <th>Logo</th>
                <th>Nom</th>
                <th colspan="2">Actions</th>
              </tr>
              </thead>
              <tbody>
              <% @brands.each do |brand| %>
                <tr>
                  <td>
                    <img src="<%= brand.logo_url %>"
                         alt="<%= %>"
                         class="img-thumbnail"
                         width="100px"
                         height="100px">
                  </td>

                  <td><%= brand.name %></td>
                  <td><%= link_to raw("<i class='fa fa-eye' aria-hidden='true'></i> Voir"), ad_brand_path(brand), class: "btn btn-primary btn-sm" %></td>
                  <td><%= link_to raw("<i class='fa fa-edit' aria-hidden='true'></i> Modifier"), edit_ad_brand_path(brand), class: "btn btn-info btn-sm" %></td>
                  <%#= link_to 'Sup', brand, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger btn-sm" %>
                </tr>
              <% end %>
              </tbody>
            </table>
            <%= will_paginate @brands %>
          </div>
        </div>
      </div>
    </div>
  </div><!-- .animated -->
</div><!-- .content -->

</div><!--DO NOT DELETE close right-panel in header.html.erb DO NOT DELETE-->

app/views/ad/brands/new.html.erb
<div class="breadcrumbs">
  <div class="col-sm-4">
    <div class="page-header float-left">
      <div class="page-title">
        <h1>
          Nouvelle marque
        </h1>
      </div>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="page-header float-right">
      <div class="page-title">
        <ol class="breadcrumb text-right">
          <li class="active">
            <%= link_to 'Marques', ad_brands_path %> / Nouveau
          </li>
        </ol>
      </div>
    </div>
  </div>
</div>
<p id="notice"><%= notice %></p>
<div class="content mt-3">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header">
            <strong class="card-title">Nouvelle marque</strong>
          </div>
          <div class="card-body">
            <div id="pay-invoice">
              <div class="card-body">
                <div class="card-title">
                  <h3 class="text-center mb-5">Nouvelle marque</h3>
                </div>
                <%= render 'form', brand: @brand %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div><!--DO NOT DELETE close right-panel in header.html.erb DO NOT DELETE-->

app/views/ad/brands/show.html.erb
<div class="breadcrumbs">
  <div class="col-sm-4">
    <div class="page-header float-left">
      <div class="page-title">
        <h1>
          <%= @brand.name %>
        </h1>
      </div>
    </div>
  </div>
  <div class="col-sm-8">
    <div class="page-header float-right">
      <div class="page-title">
        <ol class="breadcrumb text-right">
          <li class="active"><%= link_to 'Marques', ad_brands_path %> / <%= @brand.name %></li>
        </ol>
      </div>
    </div>
  </div>
</div>
<p id="notice"><%= notice %></p>
<div class="content mt-3">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <strong class="card-title">
              A propos
              <div class="float-right">
                <%= link_to raw("<i class='fa fa-edit' aria-hidden='true'></i> Modifier"), edit_ad_brand_path(@brand), class: "btn btn-info btn-sm" %>
              </div>
            </strong>
          </div>
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3 col-md-6 text-center">
                <img src="<%= @brand.logo_url %>"
                     alt="<%= %>"
                     class="img-thumbnail"
                     width="200px"
                     height="200px">
              </div>
              <div class="col-sm-9 col-md-6">
                <h4><%= @brand.name %></h4>
                <hr>
                <p><%= @brand.history %></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="content mt-3">
  <div class="animated fadeIn">
    <div class="row">
      <div class="col-md-12">
        <div class="card">
          <div class="card-header">
            <strong class="card-title">
              Liste des modèles
            </strong>
          </div>
          <div class="card-body">
            <table id="bootstrap-data-table" class="table table-striped table-bordered">
              <thead>
              <tr>
                <th>Nom</th>
                <th>Nombre de voiture</th>
                <th colspan="2">Actions</th>
              </tr>
              </thead>
              <tbody>
              <% @brand.models.each do |model| %>
                <tr>
                  <td><%= model.name %></td>
                  <td><%= model.vehicles.count %></td>
                  <td><%= link_to raw("<i class='fa fa-edit' aria-hidden='true'></i> Modifier"), edit_ad_model_path(model), class: "btn btn-info btn-sm" %></td>
                  <td><%= link_to raw("<i class='fa fa-trash' aria-hidden='true'></i> Supprimer"), model, method: :delete, data: {confirm: 'Are you sure?'}, class: "btn btn-danger btn-sm" %></td>
                </tr>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div><!--DO NOT DELETE close right-panel in header.html.erb DO NOT DELETE-->